
export const metadata = {
  title: 'about page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        <h1>Layout de About</h1>
            {children}
    </>


  )
}
